In [1]:
import os
import glob

from pathlib import Path
import shutil

import tensorflow as tf
import tf_keras as keras
import numpy as np
from tqdm import tqdm
import yaml

from rl.network import ResNet
from rl.mcts import MCTS
from rl.buffer import ReplayBuffer, Sample
from rl.game import Game, encode_state

with open("config.yaml", "r") as f:
    config = yaml.safe_load(f)

base_path = "graphs"
index = "20241130"
qubits = config["game_settings"]["N"]
training_settings = config["training_settings"]
network_settings = config["network_settings"]
mcts_settings = config["mcts_settings"]
num_cpus = training_settings["num_cpus"]
num_gpus = training_settings["num_gpus"]
n_episodes = training_settings["n_episodes"]
buffer_size = training_settings["buffer_size"]
batch_size = training_settings["batch_size"]
epochs_per_update = training_settings["epochs_per_update"]
update_period = training_settings["update_period"]
save_period = training_settings["save_period"]
eval_period = training_settings.get("eval_period", 100)


def selfplay(weights, qubits, current_episode, config):
    record = []
    game = Game(qubits, config)
    state = game.get_initial_state()
    game.reset_used_columns()
    network = ResNet(action_space=len(game.coupling_map), config=config)
    network.predict(encode_state(state, qubits))
    network.set_weights(weights)

    mcts = MCTS(qubits=qubits, network=network, config=config)
    done = False
    total_score = 0
    step_count = 0
    prev_action = None

    while not done and step_count < game.MAX_STEPS:
        mcts_policy = mcts.search(
            root_state=state,
            prev_action=prev_action,
            num_simulations=mcts_settings["num_mcts_simulations"],
        )
        if prev_action is not None:
            indices = [i for i in range(len(game.coupling_map)) if i != prev_action]
            valid_actions = game.get_valid_actions(state, prev_action)
            prob = mcts_policy[valid_actions]
            prob = prob / prob.sum()
            action = np.random.choice(valid_actions, p=prob)
        else:
            indices = list(range(len(game.coupling_map)))
            prob = mcts_policy
            action = np.random.choice(indices, p=prob)
        record.append(Sample(state.copy(), mcts_policy, reward=None))
        state, done, action_score = game.step(state, action, prev_action)
        prev_action = action
        # print(state, action_score, done)
        total_score += action_score
        step_count += 1

    reward = game.get_reward(state, total_score)
    for sample in record:
        sample.reward = reward
    return record


def evaluate_self_play(qubits, network, config):
    pattern = os.path.join(base_path, f"adj_matrix_{qubits}_*.npy")
    file_paths = glob.glob(pattern)
    avg_depth = []
    avg_counts = []
    for file_path in tqdm(file_paths):
        state = np.load(file_path)
        game = Game(qubits, config)
        swap_pairs = []
        done = False
        step_count = 0
        prev_action = None
        while not done and step_count < game.MAX_STEPS:
            encoded_state = encode_state(state, qubits)
            input_state = np.expand_dims(encoded_state, axis=0)
            policy_output, value_output = network.predict(input_state)
            policy = policy_output.numpy()[0]
            # policy = tf.nn.softmax(policy_logits).numpy()[0]
            # valid_actions = game.get_valid_actions(state, prev_action)
            if prev_action is not None:
                indices = [i for i in range(len(game.coupling_map)) if i != prev_action]
                valid_actions = game.get_valid_actions(state, prev_action)
                prob = policy[valid_actions]
                action = np.random.choice(valid_actions, p=prob / prob.sum())
            else:
                indices = list(range(len(game.coupling_map)))
                prob = policy
                action = np.random.choice(indices, p=prob / prob.sum())
            selected_action = game.coupling_map[action]
            swap_pairs.append(selected_action)
            state, done, _ = game.step(state, action, prev_action)
            prev_action = action
            step_count += 1
        if not done:
            depth = game.MAX_STEPS
            swap_count = game.MAX_STEPS
        else:
            depth = game.current_layer
            swap_count = len(swap_pairs)
        avg_counts.append(swap_count)
        avg_depth.append(depth)
    return avg_depth, avg_counts

In [2]:
logdir = Path("log")
if logdir.exists():
    shutil.rmtree(logdir)
summary_writer = tf.summary.create_file_writer(str(logdir))

game = Game(qubits, config)
network = ResNet(action_space=len(game.coupling_map), config=config)

dummy_state = encode_state(game.state, qubits)
network.predict(encode_state(game.state, qubits))
current_weights = network.get_weights()

optimizer = keras.optimizers.legacy.Adam(
    learning_rate=network_settings["learning_rate"]
)

replay = ReplayBuffer(buffer_size=buffer_size)

n_updates = 0

n = 0
while n < n_episodes:
    for _ in tqdm(range(update_period)):
        finished = selfplay(current_weights, qubits, n, config)
        replay.add_record(finished)
        n += 1
    print("-" * 50)
    if len(replay) >= batch_size:
        num_iters = epochs_per_update * (len(replay) // batch_size)
        value_loss_weight = 1
        policy_loss_weight = 1
        for i in tqdm(range(num_iters)):
            states, mcts_policy, rewards = replay.get_minibatch(batch_size=batch_size)
            with tf.GradientTape() as tape:
                p_pred, v_pred = network(states, training=True)
                value_loss = tf.square(rewards - v_pred)
                policy_loss = -tf.reduce_sum(
                    mcts_policy * tf.math.log(p_pred + 1e-5), axis=1, keepdims=True
                )
                loss = tf.reduce_mean(
                    value_loss_weight * value_loss + policy_loss_weight * policy_loss
                )
            grads = tape.gradient(loss, network.trainable_variables)
            grads, _ = tf.clip_by_global_norm(grads, 1.0)
            optimizer.apply_gradients(zip(grads, network.trainable_variables))
            n_updates += 1

            if i % 10 == 0:
                with summary_writer.as_default():
                    tf.summary.scalar(
                        "value_loss", tf.reduce_mean(value_loss), step=n_updates
                    )
                    tf.summary.scalar(
                        "policy_loss", tf.reduce_mean(policy_loss), step=n_updates
                    )

        current_weights = network.get_weights()

    if n % save_period == 0:
        network.save(f"checkpoints/network{qubits}_{index}_{n}", save_format="tf")
        network.save_weights(f"checkpoints/network{qubits}_{index}_{n}.weights.h5")
        print("-" * 50)
    if n % eval_period == 0:
        depth, count = evaluate_self_play(qubits, network, config)
        print(
            f"Episode {n}: SWAP depth is {np.mean(depth)}, SWAP count is {np.mean(count)}"
        )
        print("-" * 50)

100%|██████████| 5/5 [00:15<00:00,  3.13s/it]


--------------------------------------------------
INFO:tensorflow:Assets written to: checkpoints/network6_20241130_5/assets


INFO:tensorflow:Assets written to: checkpoints/network6_20241130_5/assets


--------------------------------------------------


  0%|          | 0/30 [00:00<?, ?it/s]/var/folders/dn/mrzg6ww170s58lpznrdv3h_00000gn/T/ipykernel_15188/1580211936.py:105: RuntimeWarning: invalid value encountered in divide
  action = np.random.choice(valid_actions, p=prob / prob.sum())
  0%|          | 0/30 [00:00<?, ?it/s]

[0. 1. 0. 0. 0.]


ValueError: probabilities contain NaN

In [3]:
game = Game(qubits, config)
network = ResNet(action_space=len(game.coupling_map), config=config)
network = keras.models.load_model(f"checkpoints/network{qubits}_{index}_{n}")

In [4]:
for _ in range(20):
    game = Game(qubits, config)
    state = game.state
    ans = []
    done = False
    total_score = 0
    step_count = 0
    prev_action = None
    print(state)
    while not done and step_count < game.MAX_STEPS:
        # 状態のエンコードと次元の調整
        encoded_state = encode_state(state, qubits)
        input_state = np.expand_dims(encoded_state, axis=0)

        # モデルによる予測
        policy_output, value_output = network.predict(input_state)
        policy = policy_output[0]
        if prev_action is not None:
            indices = [i for i in range(len(game.coupling_map)) if i != prev_action]
            prob = policy[indices]
            action = np.random.choice(indices, p=prob / prob.sum())
        else:
            indices = list(range(len(game.coupling_map)))
            action = np.random.choice(indices, p=policy)
        selected_action = game.coupling_map[action]
        ans.append(selected_action)
        state, done, _ = game.step(state, action, prev_action)
        prev_action = action
        step_count += 1
    if done:
        print(f"Game finished successfully in {step_count} steps with {ans}")
    else:
        print(f"Game terminated after reaching the maximum steps ({game.MAX_STEPS}).")
        print(f"Total score: {total_score}")

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]
1/1 [==============================] - 0s 23ms/step
Game finished successfully in 3 steps with [(1, 2), (2, 3), (3, 4)]
[[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]
1/1 [==============================] - 0s 22ms/step
Game finished successfully in 9 steps with [(2, 3), (4, 5), (0, 1), (3, 4), (1, 2), (0, 1), (4, 5), (3, 4), (1, 2)]
[[0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 0.]]
1/1 [==============================] - 0s 24ms/step
Game finished successfully in 9 steps with [(1, 2), (3, 4), (2, 3), (0, 1), (4, 5), (3, 4), (1, 2), (0, 1), (1, 2)]
[[0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0.]]
1/1 [==============================]

In [5]:
depths = []
for _ in range(10):
    depth, count = evaluate_self_play(qubits, network, config)
    depths.append(depth)
min_depth = np.min(np.vstack(depths), axis=0)

  0%|          | 0/30 [00:00<?, ?it/s]

1/1 [==============================] - 0s 23ms/step


  3%|▎         | 1/30 [00:00<00:17,  1.62it/s]

1/1 [==============================] - 0s 22ms/step


  7%|▋         | 2/30 [00:01<00:13,  2.02it/s]

1/1 [==============================] - 0s 32ms/step


 10%|█         | 3/30 [00:01<00:13,  2.06it/s]

1/1 [==============================] - 0s 23ms/step


 13%|█▎        | 4/30 [00:01<00:11,  2.22it/s]

1/1 [==============================] - 0s 22ms/step


 17%|█▋        | 5/30 [00:02<00:10,  2.41it/s]

1/1 [==============================] - 0s 23ms/step


 20%|██        | 6/30 [00:02<00:10,  2.30it/s]

1/1 [==============================] - 0s 22ms/step


 23%|██▎       | 7/30 [00:03<00:11,  2.05it/s]

1/1 [==============================] - 0s 21ms/step


 27%|██▋       | 8/30 [00:03<00:10,  2.18it/s]

1/1 [==============================] - 0s 22ms/step


 30%|███       | 9/30 [00:04<00:09,  2.22it/s]

1/1 [==============================] - 0s 22ms/step


 33%|███▎      | 10/30 [00:04<00:09,  2.17it/s]

1/1 [==============================] - 0s 24ms/step


 37%|███▋      | 11/30 [00:04<00:08,  2.32it/s]

1/1 [==============================] - 0s 23ms/step


 40%|████      | 12/30 [00:05<00:06,  2.60it/s]

1/1 [==============================] - 0s 25ms/step


 43%|████▎     | 13/30 [00:05<00:06,  2.66it/s]

1/1 [==============================] - 0s 22ms/step


 47%|████▋     | 14/30 [00:06<00:06,  2.45it/s]

1/1 [==============================] - 0s 22ms/step


 50%|█████     | 15/30 [00:06<00:06,  2.32it/s]

1/1 [==============================] - 0s 23ms/step


 53%|█████▎    | 16/30 [00:07<00:07,  1.89it/s]

1/1 [==============================] - 0s 23ms/step


 57%|█████▋    | 17/30 [00:07<00:06,  1.92it/s]

1/1 [==============================] - 0s 22ms/step


 60%|██████    | 18/30 [00:08<00:06,  1.98it/s]

1/1 [==============================] - 0s 22ms/step


 63%|██████▎   | 19/30 [00:08<00:04,  2.29it/s]

1/1 [==============================] - 0s 22ms/step


 67%|██████▋   | 20/30 [00:09<00:04,  2.04it/s]

1/1 [==============================] - 0s 22ms/step


 70%|███████   | 21/30 [00:09<00:04,  2.07it/s]

1/1 [==============================] - 0s 22ms/step


 73%|███████▎  | 22/30 [00:10<00:03,  2.31it/s]

1/1 [==============================] - 0s 23ms/step


 77%|███████▋  | 23/30 [00:10<00:03,  1.99it/s]

1/1 [==============================] - 0s 23ms/step


 80%|████████  | 24/30 [00:11<00:02,  2.06it/s]

1/1 [==============================] - 0s 24ms/step


 83%|████████▎ | 25/30 [00:11<00:02,  2.32it/s]

1/1 [==============================] - 0s 23ms/step


 87%|████████▋ | 26/30 [00:11<00:01,  2.18it/s]

1/1 [==============================] - 0s 22ms/step


 90%|█████████ | 27/30 [00:12<00:01,  1.95it/s]

1/1 [==============================] - 0s 24ms/step


 93%|█████████▎| 28/30 [00:13<00:00,  2.00it/s]

1/1 [==============================] - 0s 24ms/step


 97%|█████████▋| 29/30 [00:13<00:00,  2.02it/s]

1/1 [==============================] - 0s 22ms/step


  0%|          | 0/30 [00:00<?, ?it/s]

1/1 [==============================] - 0s 23ms/step


  3%|▎         | 1/30 [00:00<00:13,  2.15it/s]

1/1 [==============================] - 0s 23ms/step


  7%|▋         | 2/30 [00:00<00:10,  2.56it/s]

1/1 [==============================] - 0s 22ms/step


 10%|█         | 3/30 [00:01<00:12,  2.15it/s]

1/1 [==============================] - 0s 23ms/step


 13%|█▎        | 4/30 [00:01<00:12,  2.00it/s]

1/1 [==============================] - 0s 24ms/step


 17%|█▋        | 5/30 [00:02<00:12,  2.06it/s]

1/1 [==============================] - 0s 23ms/step


 20%|██        | 6/30 [00:03<00:13,  1.72it/s]

1/1 [==============================] - 0s 22ms/step


 23%|██▎       | 7/30 [00:03<00:11,  2.07it/s]

1/1 [==============================] - 0s 22ms/step


 27%|██▋       | 8/30 [00:03<00:10,  2.03it/s]

1/1 [==============================] - 0s 23ms/step


 30%|███       | 9/30 [00:04<00:10,  2.09it/s]

1/1 [==============================] - 0s 24ms/step


 33%|███▎      | 10/30 [00:05<00:11,  1.68it/s]

1/1 [==============================] - 0s 22ms/step


 37%|███▋      | 11/30 [00:05<00:10,  1.87it/s]

1/1 [==============================] - 0s 23ms/step


 40%|████      | 12/30 [00:05<00:08,  2.24it/s]

1/1 [==============================] - 0s 23ms/step


 43%|████▎     | 13/30 [00:06<00:08,  2.04it/s]

1/1 [==============================] - 0s 24ms/step


 47%|████▋     | 14/30 [00:06<00:07,  2.00it/s]

1/1 [==============================] - 0s 22ms/step


 50%|█████     | 15/30 [00:07<00:07,  2.03it/s]

1/1 [==============================] - 0s 23ms/step


 53%|█████▎    | 16/30 [00:08<00:08,  1.75it/s]

1/1 [==============================] - 0s 22ms/step


 57%|█████▋    | 17/30 [00:08<00:07,  1.80it/s]

1/1 [==============================] - 0s 23ms/step


 60%|██████    | 18/30 [00:09<00:06,  1.92it/s]

1/1 [==============================] - 0s 22ms/step


 63%|██████▎   | 19/30 [00:09<00:05,  2.18it/s]

1/1 [==============================] - 0s 23ms/step


 67%|██████▋   | 20/30 [00:10<00:04,  2.05it/s]

1/1 [==============================] - 0s 23ms/step


 70%|███████   | 21/30 [00:10<00:04,  1.88it/s]

1/1 [==============================] - 0s 22ms/step


 73%|███████▎  | 22/30 [00:11<00:03,  2.09it/s]

1/1 [==============================] - 0s 23ms/step


 77%|███████▋  | 23/30 [00:11<00:03,  1.78it/s]

1/1 [==============================] - 0s 22ms/step


 80%|████████  | 24/30 [00:12<00:03,  1.81it/s]

1/1 [==============================] - 0s 21ms/step


 83%|████████▎ | 25/30 [00:12<00:02,  1.94it/s]

1/1 [==============================] - 0s 22ms/step


 87%|████████▋ | 26/30 [00:13<00:02,  1.90it/s]

1/1 [==============================] - 0s 23ms/step


 90%|█████████ | 27/30 [00:13<00:01,  1.95it/s]

1/1 [==============================] - 0s 22ms/step


 93%|█████████▎| 28/30 [00:14<00:01,  1.77it/s]

1/1 [==============================] - 0s 21ms/step


 97%|█████████▋| 29/30 [00:14<00:00,  1.95it/s]

1/1 [==============================] - 0s 23ms/step


  0%|          | 0/30 [00:00<?, ?it/s]

1/1 [==============================] - 0s 23ms/step


  3%|▎         | 1/30 [00:00<00:13,  2.09it/s]

1/1 [==============================] - 0s 21ms/step


  7%|▋         | 2/30 [00:00<00:12,  2.33it/s]

1/1 [==============================] - 0s 24ms/step


 10%|█         | 3/30 [00:01<00:12,  2.20it/s]

1/1 [==============================] - 0s 22ms/step


 13%|█▎        | 4/30 [00:01<00:11,  2.33it/s]

1/1 [==============================] - 0s 23ms/step


 17%|█▋        | 5/30 [00:02<00:11,  2.24it/s]

1/1 [==============================] - 0s 23ms/step


 20%|██        | 6/30 [00:02<00:10,  2.20it/s]

1/1 [==============================] - 0s 23ms/step


 23%|██▎       | 7/30 [00:03<00:10,  2.11it/s]

1/1 [==============================] - 0s 22ms/step


 27%|██▋       | 8/30 [00:03<00:10,  2.10it/s]

1/1 [==============================] - 0s 23ms/step


 30%|███       | 9/30 [00:04<00:10,  2.05it/s]

1/1 [==============================] - 0s 22ms/step


 33%|███▎      | 10/30 [00:04<00:10,  1.97it/s]

1/1 [==============================] - 0s 22ms/step


 37%|███▋      | 11/30 [00:05<00:09,  2.02it/s]

1/1 [==============================] - 0s 23ms/step


 40%|████      | 12/30 [00:05<00:09,  1.90it/s]

1/1 [==============================] - 0s 21ms/step


 43%|████▎     | 13/30 [00:06<00:08,  1.92it/s]

1/1 [==============================] - 0s 23ms/step


 47%|████▋     | 14/30 [00:06<00:07,  2.04it/s]

1/1 [==============================] - 0s 22ms/step


 50%|█████     | 15/30 [00:07<00:07,  2.11it/s]

1/1 [==============================] - 0s 22ms/step


 53%|█████▎    | 16/30 [00:07<00:06,  2.01it/s]

1/1 [==============================] - 0s 22ms/step


 57%|█████▋    | 17/30 [00:08<00:06,  1.95it/s]

1/1 [==============================] - 0s 23ms/step


 60%|██████    | 18/30 [00:08<00:06,  1.86it/s]

1/1 [==============================] - 0s 25ms/step


 63%|██████▎   | 19/30 [00:09<00:05,  1.93it/s]

1/1 [==============================] - 0s 22ms/step


 67%|██████▋   | 20/30 [00:09<00:05,  1.93it/s]

1/1 [==============================] - 0s 22ms/step


 70%|███████   | 21/30 [00:10<00:04,  1.85it/s]

1/1 [==============================] - 0s 23ms/step


 73%|███████▎  | 22/30 [00:10<00:03,  2.06it/s]

1/1 [==============================] - 0s 22ms/step


 77%|███████▋  | 23/30 [00:11<00:03,  2.11it/s]

1/1 [==============================] - 0s 25ms/step


 80%|████████  | 24/30 [00:11<00:03,  1.91it/s]

1/1 [==============================] - 0s 23ms/step


 83%|████████▎ | 25/30 [00:12<00:02,  2.00it/s]

1/1 [==============================] - 0s 23ms/step


 87%|████████▋ | 26/30 [00:12<00:02,  1.96it/s]

1/1 [==============================] - 0s 23ms/step


 90%|█████████ | 27/30 [00:13<00:01,  2.00it/s]

1/1 [==============================] - 0s 24ms/step


 93%|█████████▎| 28/30 [00:13<00:01,  1.99it/s]

1/1 [==============================] - 0s 23ms/step


 97%|█████████▋| 29/30 [00:14<00:00,  1.99it/s]

1/1 [==============================] - 0s 23ms/step


  0%|          | 0/30 [00:00<?, ?it/s]

1/1 [==============================] - 0s 24ms/step


  3%|▎         | 1/30 [00:00<00:16,  1.74it/s]

1/1 [==============================] - 0s 22ms/step


  7%|▋         | 2/30 [00:00<00:13,  2.13it/s]

1/1 [==============================] - 0s 28ms/step


 10%|█         | 3/30 [00:01<00:12,  2.09it/s]

1/1 [==============================] - 0s 21ms/step


 13%|█▎        | 4/30 [00:02<00:17,  1.49it/s]

1/1 [==============================] - 0s 22ms/step


 17%|█▋        | 5/30 [00:02<00:15,  1.65it/s]

1/1 [==============================] - 0s 21ms/step


 20%|██        | 6/30 [00:03<00:13,  1.82it/s]

1/1 [==============================] - 0s 22ms/step


 23%|██▎       | 7/30 [00:03<00:11,  1.94it/s]

1/1 [==============================] - 0s 23ms/step


 27%|██▋       | 8/30 [00:04<00:11,  1.96it/s]

1/1 [==============================] - 0s 23ms/step


 30%|███       | 9/30 [00:04<00:09,  2.16it/s]

1/1 [==============================] - 0s 24ms/step


 33%|███▎      | 10/30 [00:05<00:08,  2.23it/s]

1/1 [==============================] - 0s 23ms/step


 37%|███▋      | 11/30 [00:05<00:08,  2.30it/s]

1/1 [==============================] - 0s 23ms/step


 40%|████      | 12/30 [00:05<00:07,  2.50it/s]

1/1 [==============================] - 0s 24ms/step


 43%|████▎     | 13/30 [00:06<00:06,  2.72it/s]

1/1 [==============================] - 0s 24ms/step


 47%|████▋     | 14/30 [00:06<00:06,  2.41it/s]

1/1 [==============================] - 0s 22ms/step


 50%|█████     | 15/30 [00:06<00:05,  2.60it/s]

1/1 [==============================] - 0s 23ms/step


 53%|█████▎    | 16/30 [00:07<00:06,  2.12it/s]

1/1 [==============================] - 0s 24ms/step


 57%|█████▋    | 17/30 [00:08<00:06,  1.89it/s]

1/1 [==============================] - 0s 24ms/step


 60%|██████    | 18/30 [00:08<00:06,  1.87it/s]

1/1 [==============================] - 0s 22ms/step


 63%|██████▎   | 19/30 [00:09<00:06,  1.82it/s]

1/1 [==============================] - 0s 23ms/step


 67%|██████▋   | 20/30 [00:09<00:05,  1.81it/s]

1/1 [==============================] - 0s 69ms/step


 70%|███████   | 21/30 [00:10<00:04,  1.86it/s]

1/1 [==============================] - 0s 24ms/step


 73%|███████▎  | 22/30 [00:11<00:04,  1.86it/s]

1/1 [==============================] - 0s 24ms/step


 77%|███████▋  | 23/30 [00:11<00:03,  1.97it/s]

1/1 [==============================] - 0s 23ms/step


 80%|████████  | 24/30 [00:11<00:03,  1.95it/s]

1/1 [==============================] - 0s 24ms/step


 83%|████████▎ | 25/30 [00:12<00:03,  1.62it/s]

1/1 [==============================] - 0s 23ms/step


 87%|████████▋ | 26/30 [00:13<00:02,  1.55it/s]

1/1 [==============================] - 0s 23ms/step


 90%|█████████ | 27/30 [00:14<00:01,  1.67it/s]

1/1 [==============================] - 0s 24ms/step


 93%|█████████▎| 28/30 [00:14<00:01,  1.73it/s]

1/1 [==============================] - 0s 22ms/step


 97%|█████████▋| 29/30 [00:15<00:00,  1.82it/s]

1/1 [==============================] - 0s 27ms/step


  0%|          | 0/30 [00:00<?, ?it/s]

1/1 [==============================] - 0s 23ms/step


  3%|▎         | 1/30 [00:00<00:16,  1.76it/s]

1/1 [==============================] - 0s 23ms/step


  7%|▋         | 2/30 [00:01<00:13,  2.01it/s]

1/1 [==============================] - 0s 23ms/step


 10%|█         | 3/30 [00:01<00:14,  1.82it/s]

1/1 [==============================] - 0s 23ms/step


 13%|█▎        | 4/30 [00:02<00:12,  2.04it/s]

1/1 [==============================] - 0s 22ms/step


 17%|█▋        | 5/30 [00:02<00:11,  2.14it/s]

1/1 [==============================] - 0s 24ms/step


 20%|██        | 6/30 [00:02<00:10,  2.24it/s]

1/1 [==============================] - 0s 22ms/step


 23%|██▎       | 7/30 [00:03<00:09,  2.51it/s]

1/1 [==============================] - 0s 29ms/step


 27%|██▋       | 8/30 [00:04<00:11,  1.85it/s]

1/1 [==============================] - 0s 21ms/step


 30%|███       | 9/30 [00:04<00:10,  1.94it/s]

1/1 [==============================] - 0s 22ms/step


 33%|███▎      | 10/30 [00:05<00:12,  1.60it/s]

1/1 [==============================] - 0s 22ms/step


 37%|███▋      | 11/30 [00:05<00:11,  1.64it/s]

1/1 [==============================] - 0s 23ms/step


 40%|████      | 12/30 [00:06<00:10,  1.64it/s]

1/1 [==============================] - 0s 21ms/step


 43%|████▎     | 13/30 [00:06<00:09,  1.88it/s]

1/1 [==============================] - 0s 22ms/step


 47%|████▋     | 14/30 [00:07<00:08,  1.94it/s]

1/1 [==============================] - 0s 22ms/step


 50%|█████     | 15/30 [00:07<00:06,  2.20it/s]

1/1 [==============================] - 0s 21ms/step


 53%|█████▎    | 16/30 [00:08<00:06,  2.12it/s]

1/1 [==============================] - 0s 22ms/step


 57%|█████▋    | 17/30 [00:08<00:05,  2.20it/s]

1/1 [==============================] - 0s 27ms/step


 60%|██████    | 18/30 [00:09<00:06,  1.79it/s]

1/1 [==============================] - 0s 24ms/step


 63%|██████▎   | 19/30 [00:09<00:06,  1.76it/s]

1/1 [==============================] - 0s 24ms/step


 67%|██████▋   | 20/30 [00:11<00:07,  1.38it/s]

1/1 [==============================] - 0s 22ms/step


 70%|███████   | 21/30 [00:11<00:05,  1.59it/s]

1/1 [==============================] - 0s 23ms/step


 73%|███████▎  | 22/30 [00:11<00:04,  1.68it/s]

1/1 [==============================] - 0s 21ms/step


 77%|███████▋  | 23/30 [00:12<00:04,  1.58it/s]

1/1 [==============================] - 0s 22ms/step


 80%|████████  | 24/30 [00:13<00:03,  1.79it/s]

1/1 [==============================] - 0s 20ms/step


 83%|████████▎ | 25/30 [00:13<00:02,  1.99it/s]

1/1 [==============================] - 0s 22ms/step


 87%|████████▋ | 26/30 [00:14<00:02,  1.75it/s]

1/1 [==============================] - 0s 21ms/step


 90%|█████████ | 27/30 [00:14<00:01,  1.86it/s]

1/1 [==============================] - 0s 21ms/step


 93%|█████████▎| 28/30 [00:15<00:01,  1.98it/s]

1/1 [==============================] - 0s 23ms/step


 97%|█████████▋| 29/30 [00:15<00:00,  1.73it/s]

1/1 [==============================] - 0s 23ms/step


  0%|          | 0/30 [00:00<?, ?it/s]

1/1 [==============================] - 0s 22ms/step


  3%|▎         | 1/30 [00:00<00:14,  1.95it/s]

1/1 [==============================] - 0s 22ms/step


  7%|▋         | 2/30 [00:00<00:11,  2.52it/s]

1/1 [==============================] - 0s 23ms/step


 10%|█         | 3/30 [00:01<00:11,  2.44it/s]

1/1 [==============================] - 0s 21ms/step


 13%|█▎        | 4/30 [00:01<00:10,  2.48it/s]

1/1 [==============================] - 0s 23ms/step


 17%|█▋        | 5/30 [00:02<00:10,  2.42it/s]

1/1 [==============================] - 0s 22ms/step


 20%|██        | 6/30 [00:02<00:10,  2.38it/s]

1/1 [==============================] - 0s 21ms/step


 23%|██▎       | 7/30 [00:03<00:10,  2.23it/s]

1/1 [==============================] - 0s 25ms/step


 27%|██▋       | 8/30 [00:03<00:09,  2.29it/s]

1/1 [==============================] - 0s 21ms/step


 30%|███       | 9/30 [00:03<00:09,  2.26it/s]

1/1 [==============================] - 0s 20ms/step


 33%|███▎      | 10/30 [00:04<00:08,  2.35it/s]

1/1 [==============================] - 0s 27ms/step


 37%|███▋      | 11/30 [00:04<00:08,  2.13it/s]

1/1 [==============================] - 0s 23ms/step


 40%|████      | 12/30 [00:05<00:08,  2.05it/s]

1/1 [==============================] - 0s 21ms/step


 43%|████▎     | 13/30 [00:05<00:08,  1.93it/s]

1/1 [==============================] - 0s 23ms/step


 47%|████▋     | 14/30 [00:06<00:09,  1.71it/s]

1/1 [==============================] - 0s 21ms/step


 50%|█████     | 15/30 [00:06<00:07,  2.03it/s]

1/1 [==============================] - 0s 22ms/step


 53%|█████▎    | 16/30 [00:07<00:06,  2.18it/s]

1/1 [==============================] - 0s 21ms/step


 57%|█████▋    | 17/30 [00:07<00:05,  2.30it/s]

1/1 [==============================] - 0s 20ms/step


 60%|██████    | 18/30 [00:08<00:06,  1.84it/s]

1/1 [==============================] - 0s 23ms/step


 63%|██████▎   | 19/30 [00:09<00:05,  1.86it/s]

1/1 [==============================] - 0s 21ms/step


 67%|██████▋   | 20/30 [00:09<00:05,  1.79it/s]

1/1 [==============================] - 0s 21ms/step


 70%|███████   | 21/30 [00:10<00:05,  1.63it/s]

1/1 [==============================] - 0s 21ms/step


 73%|███████▎  | 22/30 [00:10<00:04,  1.87it/s]

1/1 [==============================] - 0s 23ms/step


 77%|███████▋  | 23/30 [00:11<00:04,  1.70it/s]

1/1 [==============================] - 0s 21ms/step


 80%|████████  | 24/30 [00:12<00:03,  1.67it/s]

1/1 [==============================] - 0s 19ms/step


 83%|████████▎ | 25/30 [00:12<00:02,  1.84it/s]

1/1 [==============================] - 0s 21ms/step


 87%|████████▋ | 26/30 [00:13<00:02,  1.87it/s]

1/1 [==============================] - 0s 20ms/step


 90%|█████████ | 27/30 [00:13<00:01,  1.64it/s]

1/1 [==============================] - 0s 22ms/step


 93%|█████████▎| 28/30 [00:14<00:01,  1.85it/s]

1/1 [==============================] - 0s 21ms/step


 97%|█████████▋| 29/30 [00:14<00:00,  1.97it/s]

1/1 [==============================] - 0s 21ms/step


  0%|          | 0/30 [00:00<?, ?it/s]

1/1 [==============================] - 0s 20ms/step


  3%|▎         | 1/30 [00:00<00:17,  1.63it/s]

1/1 [==============================] - 0s 21ms/step


  7%|▋         | 2/30 [00:01<00:15,  1.86it/s]

1/1 [==============================] - 0s 23ms/step


 10%|█         | 3/30 [00:01<00:16,  1.67it/s]

1/1 [==============================] - 0s 20ms/step


 13%|█▎        | 4/30 [00:02<00:13,  1.98it/s]

1/1 [==============================] - 0s 21ms/step


 17%|█▋        | 5/30 [00:02<00:12,  2.05it/s]

1/1 [==============================] - 0s 19ms/step


 20%|██        | 6/30 [00:03<00:13,  1.77it/s]

1/1 [==============================] - 0s 21ms/step


 23%|██▎       | 7/30 [00:03<00:12,  1.84it/s]

1/1 [==============================] - 0s 21ms/step


 27%|██▋       | 8/30 [00:04<00:10,  2.08it/s]

1/1 [==============================] - 0s 20ms/step


 30%|███       | 9/30 [00:04<00:11,  1.89it/s]

1/1 [==============================] - 0s 21ms/step


 33%|███▎      | 10/30 [00:05<00:09,  2.07it/s]

1/1 [==============================] - 0s 21ms/step


 37%|███▋      | 11/30 [00:05<00:09,  2.10it/s]

1/1 [==============================] - 0s 20ms/step


 40%|████      | 12/30 [00:05<00:07,  2.29it/s]

1/1 [==============================] - 0s 21ms/step


 43%|████▎     | 13/30 [00:06<00:07,  2.25it/s]

1/1 [==============================] - 0s 21ms/step


 47%|████▋     | 14/30 [00:06<00:07,  2.28it/s]

1/1 [==============================] - 0s 21ms/step


 50%|█████     | 15/30 [00:07<00:07,  2.13it/s]

1/1 [==============================] - 0s 21ms/step


 53%|█████▎    | 16/30 [00:07<00:06,  2.09it/s]

1/1 [==============================] - 0s 21ms/step


 57%|█████▋    | 17/30 [00:08<00:05,  2.22it/s]

1/1 [==============================] - 0s 20ms/step


 60%|██████    | 18/30 [00:08<00:05,  2.09it/s]

1/1 [==============================] - 0s 20ms/step


 63%|██████▎   | 19/30 [00:09<00:04,  2.23it/s]

1/1 [==============================] - 0s 24ms/step


 67%|██████▋   | 20/30 [00:09<00:04,  2.08it/s]

1/1 [==============================] - 0s 22ms/step


 70%|███████   | 21/30 [00:10<00:03,  2.37it/s]

1/1 [==============================] - 0s 21ms/step


 73%|███████▎  | 22/30 [00:10<00:03,  2.13it/s]

1/1 [==============================] - 0s 21ms/step


 77%|███████▋  | 23/30 [00:11<00:03,  2.06it/s]

1/1 [==============================] - 0s 20ms/step


 80%|████████  | 24/30 [00:11<00:02,  2.09it/s]

1/1 [==============================] - 0s 20ms/step


 83%|████████▎ | 25/30 [00:12<00:02,  1.97it/s]

1/1 [==============================] - 0s 21ms/step


 87%|████████▋ | 26/30 [00:12<00:02,  1.97it/s]

1/1 [==============================] - 0s 20ms/step


 90%|█████████ | 27/30 [00:13<00:01,  2.08it/s]

1/1 [==============================] - 0s 20ms/step


 93%|█████████▎| 28/30 [00:13<00:00,  2.27it/s]

1/1 [==============================] - 0s 21ms/step


 97%|█████████▋| 29/30 [00:13<00:00,  2.14it/s]

1/1 [==============================] - 0s 21ms/step


  0%|          | 0/30 [00:00<?, ?it/s]

1/1 [==============================] - 0s 21ms/step


  3%|▎         | 1/30 [00:00<00:12,  2.35it/s]

1/1 [==============================] - 0s 20ms/step


  7%|▋         | 2/30 [00:00<00:11,  2.53it/s]

1/1 [==============================] - 0s 21ms/step


 10%|█         | 3/30 [00:01<00:12,  2.21it/s]

1/1 [==============================] - 0s 20ms/step


 13%|█▎        | 4/30 [00:01<00:10,  2.53it/s]

1/1 [==============================] - 0s 23ms/step


 17%|█▋        | 5/30 [00:02<00:12,  2.03it/s]

1/1 [==============================] - 0s 20ms/step


 20%|██        | 6/30 [00:02<00:12,  1.90it/s]

1/1 [==============================] - 0s 21ms/step


 23%|██▎       | 7/30 [00:03<00:12,  1.89it/s]

1/1 [==============================] - 0s 20ms/step


 27%|██▋       | 8/30 [00:03<00:10,  2.19it/s]

1/1 [==============================] - 0s 21ms/step


 30%|███       | 9/30 [00:04<00:09,  2.20it/s]

1/1 [==============================] - 0s 22ms/step


 33%|███▎      | 10/30 [00:04<00:10,  1.92it/s]

1/1 [==============================] - 0s 20ms/step


 37%|███▋      | 11/30 [00:05<00:10,  1.79it/s]

1/1 [==============================] - 0s 21ms/step


 40%|████      | 12/30 [00:05<00:08,  2.18it/s]

1/1 [==============================] - 0s 22ms/step


 43%|████▎     | 13/30 [00:06<00:07,  2.25it/s]

1/1 [==============================] - 0s 19ms/step


 47%|████▋     | 14/30 [00:06<00:07,  2.24it/s]

1/1 [==============================] - 0s 20ms/step


 50%|█████     | 15/30 [00:07<00:07,  1.94it/s]

1/1 [==============================] - 0s 20ms/step


 53%|█████▎    | 16/30 [00:07<00:07,  1.78it/s]

1/1 [==============================] - 0s 20ms/step


 57%|█████▋    | 17/30 [00:08<00:07,  1.81it/s]

1/1 [==============================] - 0s 21ms/step


 60%|██████    | 18/30 [00:08<00:06,  1.96it/s]

1/1 [==============================] - 0s 20ms/step


 63%|██████▎   | 19/30 [00:09<00:05,  1.98it/s]

1/1 [==============================] - 0s 21ms/step


 67%|██████▋   | 20/30 [00:09<00:05,  2.00it/s]

1/1 [==============================] - 0s 20ms/step


 70%|███████   | 21/30 [00:10<00:04,  1.89it/s]

1/1 [==============================] - 0s 20ms/step


 73%|███████▎  | 22/30 [00:11<00:04,  1.81it/s]

1/1 [==============================] - 0s 22ms/step


 77%|███████▋  | 23/30 [00:11<00:03,  1.93it/s]

1/1 [==============================] - 0s 21ms/step


 80%|████████  | 24/30 [00:11<00:02,  2.05it/s]

1/1 [==============================] - 0s 20ms/step


 83%|████████▎ | 25/30 [00:12<00:02,  2.26it/s]

1/1 [==============================] - 0s 20ms/step


 87%|████████▋ | 26/30 [00:12<00:01,  2.23it/s]

1/1 [==============================] - 0s 21ms/step


 90%|█████████ | 27/30 [00:13<00:01,  2.35it/s]

1/1 [==============================] - 0s 21ms/step


 93%|█████████▎| 28/30 [00:13<00:00,  2.19it/s]

1/1 [==============================] - 0s 21ms/step


 97%|█████████▋| 29/30 [00:13<00:00,  2.31it/s]

1/1 [==============================] - 0s 21ms/step


  0%|          | 0/30 [00:00<?, ?it/s]

1/1 [==============================] - 0s 24ms/step


  3%|▎         | 1/30 [00:00<00:13,  2.19it/s]

1/1 [==============================] - 0s 20ms/step


  7%|▋         | 2/30 [00:00<00:10,  2.66it/s]

1/1 [==============================] - 0s 21ms/step


 10%|█         | 3/30 [00:01<00:11,  2.42it/s]

1/1 [==============================] - 0s 20ms/step


 13%|█▎        | 4/30 [00:01<00:13,  1.95it/s]

1/1 [==============================] - 0s 20ms/step


 17%|█▋        | 5/30 [00:02<00:11,  2.09it/s]

1/1 [==============================] - 0s 20ms/step


 20%|██        | 6/30 [00:02<00:11,  2.13it/s]

1/1 [==============================] - 0s 21ms/step


 23%|██▎       | 7/30 [00:03<00:11,  2.05it/s]

1/1 [==============================] - 0s 20ms/step


 27%|██▋       | 8/30 [00:03<00:11,  1.91it/s]

1/1 [==============================] - 0s 21ms/step


 30%|███       | 9/30 [00:04<00:11,  1.86it/s]

1/1 [==============================] - 0s 21ms/step


 33%|███▎      | 10/30 [00:04<00:09,  2.16it/s]

1/1 [==============================] - 0s 23ms/step


 37%|███▋      | 11/30 [00:05<00:09,  2.11it/s]

1/1 [==============================] - 0s 21ms/step


 40%|████      | 12/30 [00:05<00:07,  2.26it/s]

1/1 [==============================] - 0s 19ms/step


 43%|████▎     | 13/30 [00:06<00:07,  2.18it/s]

1/1 [==============================] - 0s 21ms/step


 47%|████▋     | 14/30 [00:06<00:08,  1.99it/s]

1/1 [==============================] - 0s 20ms/step


 50%|█████     | 15/30 [00:07<00:08,  1.80it/s]

1/1 [==============================] - 0s 22ms/step


 53%|█████▎    | 16/30 [00:07<00:07,  1.93it/s]

1/1 [==============================] - 0s 20ms/step


 57%|█████▋    | 17/30 [00:08<00:06,  2.15it/s]

1/1 [==============================] - 0s 20ms/step


 60%|██████    | 18/30 [00:08<00:05,  2.11it/s]

1/1 [==============================] - 0s 21ms/step


 63%|██████▎   | 19/30 [00:09<00:05,  2.09it/s]

1/1 [==============================] - 0s 20ms/step


 67%|██████▋   | 20/30 [00:09<00:05,  1.94it/s]

1/1 [==============================] - 0s 21ms/step


 70%|███████   | 21/30 [00:10<00:04,  1.98it/s]

1/1 [==============================] - 0s 21ms/step


 73%|███████▎  | 22/30 [00:10<00:04,  1.96it/s]

1/1 [==============================] - 0s 20ms/step


 77%|███████▋  | 23/30 [00:11<00:03,  2.03it/s]

1/1 [==============================] - 0s 20ms/step


 80%|████████  | 24/30 [00:11<00:02,  2.19it/s]

1/1 [==============================] - 0s 20ms/step


 83%|████████▎ | 25/30 [00:12<00:02,  2.14it/s]

1/1 [==============================] - 0s 20ms/step


 87%|████████▋ | 26/30 [00:12<00:01,  2.06it/s]

1/1 [==============================] - 0s 20ms/step


 90%|█████████ | 27/30 [00:12<00:01,  2.26it/s]

1/1 [==============================] - 0s 20ms/step


 93%|█████████▎| 28/30 [00:13<00:00,  2.13it/s]

1/1 [==============================] - 0s 20ms/step


 97%|█████████▋| 29/30 [00:13<00:00,  2.16it/s]

1/1 [==============================] - 0s 21ms/step


  0%|          | 0/30 [00:00<?, ?it/s]

1/1 [==============================] - 0s 21ms/step


  3%|▎         | 1/30 [00:00<00:14,  2.02it/s]

1/1 [==============================] - 0s 20ms/step


  7%|▋         | 2/30 [00:00<00:12,  2.24it/s]

1/1 [==============================] - 0s 21ms/step


 10%|█         | 3/30 [00:01<00:13,  1.93it/s]

1/1 [==============================] - 0s 21ms/step


 13%|█▎        | 4/30 [00:01<00:11,  2.30it/s]

1/1 [==============================] - 0s 21ms/step


 17%|█▋        | 5/30 [00:02<00:11,  2.27it/s]

1/1 [==============================] - 0s 20ms/step


 20%|██        | 6/30 [00:02<00:10,  2.32it/s]

1/1 [==============================] - 0s 22ms/step


 23%|██▎       | 7/30 [00:03<00:11,  2.04it/s]

1/1 [==============================] - 0s 22ms/step


 27%|██▋       | 8/30 [00:03<00:10,  2.07it/s]

1/1 [==============================] - 0s 21ms/step


 30%|███       | 9/30 [00:04<00:10,  2.09it/s]

1/1 [==============================] - 0s 22ms/step


 33%|███▎      | 10/30 [00:04<00:11,  1.77it/s]

1/1 [==============================] - 0s 21ms/step


 37%|███▋      | 11/30 [00:05<00:09,  2.00it/s]

1/1 [==============================] - 0s 21ms/step


 40%|████      | 12/30 [00:05<00:08,  2.14it/s]

1/1 [==============================] - 0s 22ms/step


 43%|████▎     | 13/30 [00:06<00:07,  2.34it/s]

1/1 [==============================] - 0s 21ms/step


 47%|████▋     | 14/30 [00:06<00:06,  2.35it/s]

1/1 [==============================] - 0s 22ms/step


 50%|█████     | 15/30 [00:06<00:06,  2.36it/s]

1/1 [==============================] - 0s 20ms/step


 53%|█████▎    | 16/30 [00:07<00:05,  2.57it/s]

1/1 [==============================] - 0s 21ms/step


 57%|█████▋    | 17/30 [00:07<00:05,  2.45it/s]

1/1 [==============================] - 0s 21ms/step


 60%|██████    | 18/30 [00:08<00:05,  2.30it/s]

1/1 [==============================] - 0s 20ms/step


 63%|██████▎   | 19/30 [00:08<00:04,  2.52it/s]

1/1 [==============================] - 0s 21ms/step


 67%|██████▋   | 20/30 [00:08<00:04,  2.34it/s]

1/1 [==============================] - 0s 21ms/step


 70%|███████   | 21/30 [00:09<00:03,  2.40it/s]

1/1 [==============================] - 0s 20ms/step


 73%|███████▎  | 22/30 [00:09<00:03,  2.46it/s]

1/1 [==============================] - 0s 21ms/step


 77%|███████▋  | 23/30 [00:10<00:03,  2.06it/s]

1/1 [==============================] - 0s 21ms/step


 80%|████████  | 24/30 [00:10<00:02,  2.00it/s]

1/1 [==============================] - 0s 21ms/step


 83%|████████▎ | 25/30 [00:11<00:02,  1.90it/s]

1/1 [==============================] - 0s 21ms/step


 87%|████████▋ | 26/30 [00:12<00:02,  1.88it/s]

1/1 [==============================] - 0s 20ms/step


 90%|█████████ | 27/30 [00:12<00:01,  1.95it/s]

1/1 [==============================] - 0s 21ms/step


 93%|█████████▎| 28/30 [00:12<00:00,  2.10it/s]

1/1 [==============================] - 0s 21ms/step


 97%|█████████▋| 29/30 [00:13<00:00,  2.34it/s]

1/1 [==============================] - 0s 21ms/step


100%|██████████| 30/30 [00:13<00:00,  2.18it/s]
